// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTH_q3e0dLC8Tr9t4Q2XUXNWLmhzVDduA',
    appId: '1:548648002546:web:74f9eaf10e4a9ef1ba016b',
    messagingSenderId: '548648002546',
    projectId: 'recovery-buddy-398222',
    authDomain: 'recovery-buddy-398222.firebaseapp.com',
    storageBucket: 'recovery-buddy-398222.appspot.com',
    measurementId: 'G-JPZNPG3ES1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29W6FEOkP_CB8jO3HdY30xg08nW1yTz8',
    appId: '1:548648002546:android:430ec3522859c352ba016b',
    messagingSenderId: '548648002546',
    projectId: 'recovery-buddy-398222',
    storageBucket: 'recovery-buddy-398222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWWKeY31_MX99G0D2Mttx6vPrI9ZJb5B0',
    appId: '1:548648002546:ios:3f96d460396142f9ba016b',
    messagingSenderId: '548648002546',
    projectId: 'recovery-buddy-398222',
    storageBucket: 'recovery-buddy-398222.appspot.com',
    iosClientId: '548648002546-0a8or00kgi85kftch3c9q6mfs40e4d6u.apps.googleusercontent.com',
    iosBundleId: 'com.guo.recoverybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWWKeY31_MX99G0D2Mttx6vPrI9ZJb5B0',
    appId: '1:548648002546:ios:a42195ec25b89793ba016b',
    messagingSenderId: '548648002546',
    projectId: 'recovery-buddy-398222',
    storageBucket: 'recovery-buddy-398222.appspot.com',
    iosClientId: '548648002546-1arhpod978hnh64lepre5dkej14fh0iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.stretchsafe.RunnerTests',
  );
}
